language: go

go: 
  - 1.8

services:
  - postgresql

before_script:
  - psql -c "create role ptotest with password 'helpful guide sheep train';" -U postgres
  - psql -c "create database ptotest;" -U postgres
  - psql -c "grant create on database ptotest to ptotest;" -U postgres



